CREATE DATABASE HospitalManagement;
USE HospitalManagement;

CREATE TABLE IF NOT EXISTS PATIENT (
PatientSSN DECIMAL(50),
PatientFirstName VARCHAR(50) NOT NULL,
PatientLastName VARCHAR(50) NOT NULL,
PatientAge DECIMAL(3,0) NOT NULL,
PatientAddress VARCHAR(100),
Pass VARCHAR(50) NOT NULL,
PatientPhoneNumber DECIMAL(8,0),
PatientFamilyNumber DECIMAL(8,0),
Entdate DATE,
Leavedate DATE,
Reg_time TIME,
Reg_date DATE,
StaffID DECIMAL(5,0),
DoctorID DECIMAL(5,0),
RoomNb DECIMAL(4,0),
PRIMARY KEY(PatientID)
);

CREATE TABLE IF NOT EXISTS STAFF (
StaffID DECIMAL(5,0),
StaffFirstName VARCHAR(50) NOT NULL,
StaffLastName VARCHAR(50) NOT NULL,
Pass VARCHAR(50) NOT NULL,
StaffSpecialization VARCHAR(50) NOT NULL,
StaffAddress VARCHAR(100),
StaffPhoneNumber DECIMAL(8,0),
PRIMARY KEY(StaffID)
);

CREATE TABLE IF NOT EXISTS DOCTOR (
DoctorID DECIMAL(5,0),
DoctorFirstName VARCHAR(50) NOT NULL,
DoctorLastName VARCHAR(50) NOT NULL,
DoctorAge DECIMAL(3,0),
DoctorSpecialization VARCHAR(50) NOT NULL,
DoctorAddress VARCHAR(100),
DoctorPhoneNumber DECIMAL(8,0),
PRIMARY KEY(DoctorID)
);

CREATE TABLE IF NOT EXISTS NURSE (
NurseID DECIMAL(5,0),
NurseFirstName VARCHAR(50) NOT NULL,
NurseLastName VARCHAR(50) NOT NULL,
NurseAge DECIMAL(3,0),
NurseSpecialization VARCHAR(50) NOT NULL,
NurseAddress VARCHAR(100),
NursePhoneNumber DECIMAL(8,0),
PRIMARY KEY(NurseID)
);

CREATE TABLE IF NOT EXISTS MEDICINE (
MedicineName VARCHAR(50),
MedicineType VARCHAR(50) NOT NULL,
MedicineBarcode VARCHAR(100),
CompanyName VARCHAR(100),
ExpiryDate DATE,
MedicinePrice DECIMAL(8,0),
DoctorID DECIMAL(5,0),
PRIMARY KEY(MedicineName,MedicineBarcode)
);

CREATE TABLE IF NOT EXISTS BILL (
BillID DECIMAL(5,0),
Taxes DECIMAL (5,0) NOT NULL,
BillDetails VARCHAR(100) NOT NULL,
Currency VARCHAR(50),
BillStatus VARCHAR(50),
BillAmount DECIMAL(9,0),
PRIMARY KEY(BillID)
);

CREATE TABLE IF NOT EXISTS MEDICALRECORD (
MedicalRecordID DECIMAL(5,0),
PatientGender CHAR,
Disease VARCHAR(50),
DiagnosisYear YEAR,
PreviousSurgeries VARCHAR(100),
Allergies VARCHAR(100) NOT NULL,
BloodType VARCHAR(3) NOT NULL,
BloodTest VARCHAR(100),
VaccinationHistory VARCHAR(100),
Symptoms VARCHAR(100),
record_time TIME,
PatientID DECIMAL(5,0),
PRIMARY KEY(MedicalRecordID)
);

CREATE TABLE IF NOT EXISTS FLOOR (
FloorNb DECIMAL(2,0),
NumberofRooms DECIMAL(3,0),
NumberofBeds DECIMAL(2,0),
PRIMARY KEY(FloorNb)
);

CREATE TABLE IF NOT EXISTS ROOM (
RoomNb DECIMAL(4,0),
RoomUsage VARCHAR(50),
Availibility VARCHAR(4) Not Null,
RoomLevel DECIMAL(2,0) CHECK(RoomLevel BETWEEN 1 AND 99),
RommClass VARCHAR(3),
NumberofBeds DECIMAL(2,0) CHECK(NumberofBeds BETWEEN 1 AND 99),
NumberofEquipments DECIMAL(3,0) CHECK(NumberofEquipments BETWEEN 1 AND 999),
FloorNb DECIMAL(2,0),
PRIMARY KEY(RoomNb)
);

CREATE TABLE IF NOT EXISTS APPOINTMENT(
App_nb DECIMAL(4,0),
PatientID DECIMAL(5,0),
DoctorID DECIMAL(5,0),
App_date DATE,
App_time TIME,
App_status VARCHAR(100),
PRIMARY KEY (App_nb, PatientID, DoctorID),
FOREIGN KEY (PatientID) REFERENCES PATIENT(PatientID),
FOREIGN KEY (DoctorID) REFERENCES DOCTOR(DoctorID)
);

CREATE TABLE IF NOT EXISTS TAKE(
Medicine_time TIME,
PatientID DECIMAL(5,0),
Medicine_name VARCHAR(50),
PRIMARY KEY (Medicine_time, PatientID, Medicine_name),
FOREIGN KEY (PatientID) REFERENCES PATIENT(PatientID),
FOREIGN KEY (Medicine_name) REFERENCES MEDICINE(MedicineName)
);

CREATE TABLE IF NOT EXISTS REGISTRATION(
Reg_time TIME,
Reg_date DATE,
PatientID DECIMAL(5,0),
StaffID DECIMAL(5,0),
PRIMARY KEY (Reg_date, PatientID, StaffID),
FOREIGN KEY (PatientID) REFERENCES PATIENT(PatientID),
FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID)
);

CREATE TABLE IF NOT EXISTS PAYMENT(
Pay_time TIME,
BillID DECIMAL(5,0),
PatientID DECIMAL(5,0),
MedicineName VARCHAR(50),
PRIMARY KEY (Pay_time, BillID, PatientID, MedicineName),
FOREIGN KEY (PatientID) REFERENCES PATIENT(PatientID),
FOREIGN KEY (BillID) REFERENCES BILL(BillID),
FOREIGN KEY (MedicineName) REFERENCES MEDICINE(MedicineName)
);

CREATE TABLE IF NOT EXISTS CONTAINT(
NurseID DECIMAL(5,0),
Working_year YEAR,
FloorNb DECIMAL(2,0),
DoctorID DECIMAL(5,0),
PRIMARY KEY (Working_year, DoctorID, NurseID, FLoorNb),
FOREIGN KEY (DoctorID) REFERENCES DOCTOR(DoctorID),
FOREIGN KEY (NurseID) REFERENCES NURSE(NurseID),
FOREIGN KEY (FloorNb) REFERENCES FLOOR(FloorNb)
);
ALTER TABLE PATIENT
ADD FOREIGN KEY (RoomNb) REFERENCES ROOM(RoomNb);
ALTER TABLE PATIENT
ADD FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID);
ALTER TABLE PATIENT
ADD FOREIGN KEY (DoctorID) REFERENCES DOCTOR(DoctorID);

ALTER TABLE ROOM
ADD FOREIGN KEY (FloorNb) REFERENCES FLOOR(FloorNb);

ALTER TABLE MEDICALRECORD
ADD FOREIGN KEY (PatientID) REFERENCES PATIENT(PatientID);

ALTER TABLE MEDICINE
ADD FOREIGN KEY (DoctorID) REFERENCES DOCTOR(DoctorID);

